project:
  type: website
  output-dir: docs

website:
  title: "Karthi's Blog"
  navbar:
    right:
      - about.qmd
      - icon: twitter
        href: https://twitter.com/AI_Swordsman
format:
  html:
    theme: zephyr
    css: styles.css



